spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

adapter:
  micro-users:
    url: ${USERS_SERVICE_URL}
  micro-messaging:
    url: ${MESSAGING_SERVICE_URL}
  micro-traceability:
    url: ${TRACEABILITY_SERVICE_URL}

feign:
  client:
    config:
      micro-users:
        connectTimeout: 5000
        readTimeout: 5000
      micro-messaging:
        connectTimeout: 5000
        readTimeout: 5000
      micro-traceability:
        connectTimeout: 5000
        readTimeout: 5000

jwt:
  secret: ${JWT_SECRET}